### ISSUE TITLE
Battlefield V crashes at launch with dxr enabled 

### ISSUE THREAD

**Issue by Idcrafter** [HansKristian-Work/vkd3d-proton#1017]
it always crashes when dxr is enabled

**Comment by doitsujin** [comment]
Thank you very much for providing such detailed information about your hardware, driver, operating system, and vkd3d-proton logs.

**Comment by Idcrafter** [comment]
i have a rtx 2060 with 510 nvidia drivers ryzen 5 3600 with 48gb ddr4 ddr3600 cl16  Asus B450-f mainboard

**Comment by ProjectSynchro** [comment]
> Thank you very much for providing such detailed information about your hardware, driver, operating system, and vkd3d-proton logs. We can totally fix this based on the report alone!

I just had a go at reproducing this (granted I don't have NVIDIA hardware), and I do indeed get a crash.
I'm currently running:
RX 6900XT
Mesa 23.0.0-git commit:6cab999
Fedora 36 Workstation (Kernel 5.18.4-xm1.0 XanMod)
VKD3D-proton 2.6.0 (Whatever is currently shipping with Proton Experimental)


I initially ran the game via Steam using the launch option `RADV_PERFTEST=rt VKD3D_CONFIG=dxr %command%` in order to expose the correct ray tracing features. 

Enabling DX12 and DXR in the game settings causes the game to crash after restarting the game to apply changes.
It craps out just as it starts setting the window size.

With `VKD3D_DEBUG=err` set I get the following in my log `0848:err:d3d12_state_object_parse_subobjects: Must have shader config.`. I attached [a log file](https://github.com/HansKristian-Work/vkd3d-proton/files/8962527/BattlefieldVDXR.log) with `VKD3D_DEBUG` set to `warn` as there is a bunch more noise in this log.

I do know that in Windows, this game does not work correctly with AMD hardware as the game may depend on some NVIDIA specific stuff for ray tracing. (See [this post on the EA help forums](https://answers.ea.com/t5/Battlefield-V/Ray-tracing-with-no-reflections-in-battlefield-V-and-AMD/m-p/10663609/highlight/true#M77786))

Let me know if I can provide more information or better logs. (I don't know how helpful the one I provided is.)

**Comment by jkrhu** [comment]
The problem is still occuring. Crashes during the initial loading when DXR is enabled. DX11 and DX12 is fine, as long as DXR is off. Tried changing the config to just `=dxr`, removing the `FEATURE_LEVEL`, but makes no difference.

Specs:
Fedora 36, 6.0.5 kernel 
RTX 3060 
Driver 520.56.06 
i5 10400
16GB RAM

Commands: `VKD3D_CONFIG=dxr11 VKD3D_FEATURE_LEVEL=12_1 PROTON_ENABLE_NVAPI=1 PROTON_HIDE_NVIDIA_GPU=0`

Attaching the log file below:
[BFV DXR Nvidia.log](https://github.com/HansKristian-Work/vkd3d-proton/files/9924530/BFV.DXR.Nvidia.log)

**Comment by K0bin** [comment]
> 0af8:err:d3d12_state_object_pipeline_data_find_global_state_object: Mismatch in inherited associations for kind 1.

This is probably the interesting one.

**Comment by NikTech06** [comment]
> That seems to be the case for BF5.

is there anything i can do about that? Fucking h8 windows and don't wanna go back to it.

**Comment by HansKristian-Work** [comment]
I would have to somehow implement that API wart. It's really hard and I don't know when I'll be able to, but I'll have to do it eventually.
