### ISSUE TITLE
Elden Ring on Win7 GTX 970 has 5 fps

### ISSUE THREAD

**Issue by mhmarf** [HansKristian-Work/vkd3d-proton#1019]
Hello.
I'm (and many more) trying to play Elden Ring on Win7 and GTX 970 using [this mod](https://www.nexusmods.com/eldenring/mods/12) which uses DXVK's dxgi.dll and VKD3D-Proton 2.3.1 but cannot get more than 5 fps and game runs in slow motion...
Apparently nvidia users cannot benefit from VKD3D as opposed to amd users who it seems do not have this low fps problem.
Can anything be done? Will changing OS to Linux change anything?
Thanks
[eldenring_dxgi.log](https://github.com/HansKristian-Work/vkd3d-proton/files/8147708/eldenring_dxgi.log)
.

**Comment by Blisto91** [comment]
@mhmarf you could try with the latest vkd3d-proton master build
https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/1899995433

But note the main focus of vkd3d-proton is Linux so they probably won't focus on windows support.
I can't say if running Linux instead would give you a difference since it has its own overhead. Also the game seems to have some optimization issues even for some people with powerull pc's

**Comment by mhmarf** [comment]
Trying this build resulted in a white screen into crash to desktop. Will try asking author of Elden Ring Win7 mod to provide a patch for it and will report the results.
Thanks.

**Comment by Blisto91** [comment]
Ah i see. I get the same issue on Linux through Proton. Though my R9 380 is technically below min spec so haven't really looked into it. 
As the [devs said in this other thread](https://github.com/HansKristian-Work/vkd3d-proton/issues/1016) they don't believe that is a vkd3d issue (i don't either since it also happens for me with WINED3D)

**Comment by SveSop** [comment]
The main goal (as said) of vkd3d is not to get this working with Win7.
You could experiment with M$ own D3D12on7 package perhaps?
[https://microsoft.github.io/DirectX-Specs/d3d/D3D12onWin7.html#faq](https://microsoft.github.io/DirectX-Specs/d3d/D3D12onWin7.html#faq)
[https://www.nuget.org/packages/Microsoft.Direct3D.D3D12On7](https://www.nuget.org/packages/Microsoft.Direct3D.D3D12On7)
Supposedly the "nuget" package can be renamed to .zip and extracted into the game folder... Not tested this, but "people" have tried :)

**Comment by Ryusennin** [comment]
@mhmarf In your case, you should give a try to this library:
https://github.com/tuffee88/d3d12ProxyEdrDx11_0

**Comment by mhmarf** [comment]
@Ryusennin
I've already tried it and got white screen crash. Without it I can get into the game (tho 5 fps).Also my gpu does support DX12 so don't think that library is even related to me. Though it has enabled people with old DX11 cards to run the game with 40 fps but they are on Win 10 not Win 7.Thank you for your help.
    On Sunday, March 6, 2022, 04:34:10 AM GMT+3:30, Ryusennin ***@***.***> wrote:  
 
 


@mhmarf In your case, you should give a try to this library:
https://github.com/tuffee88/d3d12ProxyEdrDx11_0

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TheApprentice6** [comment]
I'm on Windows 10 the game works fine on DX12 with some frame drops, but for some reason newest version of VKD3D doesn't work the game opens and it closes, some older version works but really bad, did anyone get Elden Ring or any other DX12 game to work on the newest VKD3D?

**Comment by doitsujin** [comment]
The game works fine with vkd3d-proton on Linux.

**Comment by Wintermute00** [comment]
@mhmarf 
vkd3d can still work on Windows if you follow these instruction.
https://www.youtube.com/watch?v=I0Fq9qGk0zQ
