### ISSUE TITLE
Shadow of the Tomb Raider fails to bring up game menu

### ISSUE THREAD

**Issue by jhu54** [HansKristian-Work/vkd3d-proton#1214]
Epic Games has Shadow of the Tomb Raider as a free game this week so I thought I would add it to my collection. Running with the latest Git releases of DXVK and VKD3D (running Epic Games Launcher through Lutris or Steam with most recent GE proton/wine builds). Initial launch will fail with DirectX 12 enabled in the SotTR launcher (this is the default). Setting DirectX 11 in the options on the launcher, the game runs fine. On subsequent launching from EPS, and enabling the DirectX 12 option, the credits screen will load fine, but will crash prior to showing the Game Menu.

When I get back to the computer tomorrow, I will see if I can get more details. Posting this now as the game is free on Epic Games Store so getting a copy of the game will be easy. And yes I know there is a native version on Steam, the free deal may interest others to grab it on EPS and see this issue.

**Comment by K0bin** [comment]
Please upload your VKD3D-Proton log file.

**Comment by doitsujin** [comment]
And also mention your hardware etc.

If this is on RADV: Yes, known issue, game requires sparse depth images which the driver does not support. `VKD3D_FEATURE_LEVEL=11_1` **might** be enough to work around this.

In general, this is not a high-priority issue since the game has a very good native Linux build.

**Comment by jhu54** [comment]
Sorry on Sydney Harbour tonight. Yes know that the native works well. Yes
radv, not a huge priority for me.

More wanted a note here for anyone else who is getting the free version
from Epic to understand the issues and existence of a native version or use
DirectX 11. This will show up should anyone search for the game not working
through Heroic game launcher or other means.

Happy if someone wants to close this.

**Comment by bjornfor** [comment]
> Closing this - native version runs exceptionally well and if anyone does want to use the Epic Games version or other, simply changing to DirectX 11 in the game launcher will give a good game experience.

@jhu54: Can I ask what software versions you have?

I also have RX 6700 XT. In Steam I'm trying to run the game with both Proton (experimental, 7.0-4) and Linux native version. All have rapid texture flickering (z-fighting?) on character bodies (except face), similar to [here](https://www.warwithpc.com/2021/12/shadow-of-tomb-raider-game-texture-shutters-flickering.html). I've looked around the internet and it seems more people have similar issues ([reddit](https://www.reddit.com/r/Amd/comments/mj3d5g/investigating_flickering_shadowstextures_in_some/), [protondb](https://www.protondb.com/app/750920#pdh-2ArjJX)). I came here since one of the URLs claimed the issue was fixed switching to dx12 (a Windows user). But when dx12 is enabled the game fails to launch in Steam on Linux with Proton.

My software:
* NixOS 22.05
* Linux 5.15.67
* `vulkaninfo` shows I'm using MESA RADV driver, version 22.0.4.
* (Anything else that matters?)

**Comment by bjornfor** [comment]
> [...] rapid texture flickering (z-fighting?) on character bodies (except face) [...]

Turns out it was a distro packaging issue where mesa 00-radv-defaults.conf (containing game specific workarounds) wasn't picked up. It's fixed now and I can play the game :tada:
