### ISSUE TITLE
Witcher 3 v 4.00 - turning on RTX locks up the game.

### ISSUE THREAD

**Issue by melonlm** [HansKristian-Work/vkd3d-proton#1342]
Distro: Arch
Proton: bleeding edge beta from steam
NVidia driver: 525.60.11-3 with PROTON_ENABLE_NGX_UPDATER=1 set

Game works fine with RTX turned off. turning RTX on reliably produces following error visible in steam stdout/stderr output:
`winevulkan/virtual_queue_worker: queue submission failed with -4, treating as DEVICE_LOST.`
It seems to also produce a correlated dmesg entry:
`[  973.501169] NVRM: Xid (PCI:0000:29:00): 109, pid=2503, name=witcher3.exe, Ch 0000002b, errorString CTX SWITCH TIMEOUT, Info 0x1cc029`

With yesterday's Proton (without 2.8 vkd3d) it produced a different error I failed to capture verbatim, but it included a fencing timeout.

**Comment by melonlm** [comment]
One more thing: according to ncvidia-smi output the witcher3 processa seems to want to gobble up ALL the video memory:
```+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.11    Driver Version: 525.60.11    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:29:00.0 Off |                  N/A |
|  0%   48C    P8    24W / 220W |   7714MiB /  8192MiB |      6%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       892    C+G   sway                              102MiB |
|    0   N/A  N/A      1054      G   Xwayland                            3MiB |
|    0   N/A  N/A      1332    C+G   ... --enable-features=Vulkan       11MiB |
|    0   N/A  N/A      1990      G   ...e/Steam/ubuntu12_32/steam      139MiB |
|    0   N/A  N/A      2044      G   ...ef_log.txt --shared-files      170MiB |
|    0   N/A  N/A      2503    C+G   ...bin\x64_dx12\witcher3.exe     7187MiB |
+-----------------------------------------------------------------------------+```

**Comment by K0bin** [comment]
A game using 8GB of VRAM when doing RT really doesn't sound that crazy to me. I don't think that's part of the issue.

**Comment by melonlm** [comment]
well it's happy on windows with same resources

pt., 16 gru 2022 o 20:51 Robin Kertels ***@***.***>
napisał(a):

**Comment by K0bin** [comment]
Yes, it's a known issue. It does an out of bounds read from the SRV descriptor heap. We don't know what causes it however.

**Comment by extract** [comment]
Is this the tracker or is there another place I can follow progress?

**Comment by K0bin** [comment]
#1353 fixes one issue with it but it still hangs because of a problem with synchronization.

Don't expect any progress on that, everyone is on vacation.

**Comment by jrgiacone** [comment]
Just checking on this one if there is any tests I can help run to provide logs. If that would help?

**Comment by K0bin** [comment]
Nope, nothing you can do.

**Comment by Blisto91** [comment]
Just noting here that i have not experienced this issue on my 7900XTX

**Comment by catfish-k** [comment]
Xid (PCI:0000:01:00): 109, pid=338233, name=Warframe.x64.ex, Ch 000000be, errorString CTX SWITCH TIMEOUT, Info 0x1c06a

Rolling back to version 520.56.06 Nvidia kernel modules and a 6.0.1 series kernel fixed it. I got the hint from this dev post:

https://forums.developer.nvidia.com/t/multiple-cuda-rtx-vulkan-application-crashing-with-xid-13-109-errors/235459/33

**Comment by struq** [comment]
RT seems to be working fine now with vkd3d 2.9, nvidia 530.41.03, and game version 4.03.

**Comment by urbenlegend** [comment]
@struq There's still some issues with RT. In particular, having it enabled when you start the beginning of the game causes really low framerates (< 5fps) during the scene where Geralt gets out of the bath tub and approaches Yennifer.

**Comment by struq** [comment]
Just watched again the scene you mentioned and no problem here. The entire opening scene maintains 30~40 fps (1080p) for me, not great but also not very different from Windows. That being said, I do sometimes get sudden framerate drops with the dx12 version, whether or not with RT enabled, that doesn't recover unless it's restarted. But that happens in Windows too and doesn't look like a vkd3d-proton issue.

**Comment by adolfotregosa** [comment]
> RT seems to be working fine now with vkd3d 2.9, nvidia 530.41.03, and game version 4.03.

shadows are not ok with RT enabled

**Comment by struq** [comment]
> shadows are not ok with RT enabled

Yes, I see the shadow glitches too. Likely the same as https://github.com/HansKristian-Work/vkd3d-proton/issues/1373.

**Comment by CarlKath** [comment]
How did you guys get the game to load with ray tracing?
My instance just hangs after loading.

**Comment by neworld** [comment]
> How did you guys get the game to load with ray tracing?

I managed to launch the game by lowering the resolution to 1440p. It worked until I went to the city. I suppose I need to use `RT` settings instead of `RT Ultra`. However, the game stopped working at all, so it could be a coincidence. 

Witcher version: 4.0.4
GPU: 3080 ti
Latest drivers and everything

**Comment by Blisto91** [comment]
> Just noting here that i have not experienced this issue on my 7900XTX and i am able to turn on RT (tho perf and frame timing is pretty bad)

Correction to that. I cannot seem to load in to Blood and Wine without a GPU hang no matter radv or amdvlk.
Regular game doesn't seem to complain so far in that regard, but it's mostly been spot testing here and there so maybe it can also happen in certain locations.

**Comment by kostea92** [comment]
The Witcher 3 next-gen — RT freeze on NVIDIA/Linux (Xid 109): FIXED with extra_rtas_sync

  Launch options that fixed it:
  PROTON_ENABLE_NVAPI=1 VKD3D_CONFIG=extra_rtas_sync %command%

  SYMPTOM
  Enabling ray tracing (DX12) freezes the picture within seconds while audio keeps
  playing. Kernel log shows:
    NVRM: Xid (PCI:0000:01:00): 109, name=witcher3.exe, CTX SWITCH TIMEOUT
  Game must be killed from a terminal.

  SYSTEM
  RTX 3060 12GB / driver 610.43.03 (open module) / CachyOS kernel 7.1.4 / KDE Wayland
  GE-Proton11-1 (vkd3d-proton 1.1-5388-gbee300e4c)

  RULED OUT (all tested)
  - Mods: crashes with -disablemods too
  - Resolution: crashes at 1080p
  - GPU load / weak GPU: CRASHES IN THE MENU the instant the RT toggle is flipped
  - VRAM: only 3-6 GB of 12 in use
  - Clocks: nvidia-smi -lgc 210,1800 changed nothing
  - Proton version: GE freezes on a frame, Experimental gives black screen + audio
  - VKD3D_CONFIG=single_queue / no_upload_hvv / force_host_cached: no fix
  - VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_wait: no fix

  ROOT CAUSE
  PROTON_LOG=1 VKD3D_DEBUG=warn showed, ~10s before VK_ERROR_DEVICE_LOST:
    vkd3d_va_map_place_acceleration_structure: Attempted to place non-TLAS on
    VA #14ba05a00 previously used by TLAS, marking mutated
  The game reuses TLAS memory without inserting barriers, so rays traverse an
  invalid BVH and stall the RT core -> GPU context switch timeout.
  extra_rtas_sync inserts the RTAS barriers the game omits.

  CAVEATS
  - Mitigation, not a cure: an Xid 109 can still fire, but the GPU now recovers
    and the game survives instead of hanging dead.
  - If hangs persist, try: VKD3D_CONFIG=extra_rtas_sync,single_queue
  - ALT-TAB still kills the session (swapchain never restores, black screen).
  - Ignore old guides recommending VKD3D_CONFIG=dxr,dxr11 — those options no
    longer exist in modern vkd3d-proton.
