### ISSUE TITLE
Metro Exudos Enhanced edition crashes on startup

### ISSUE THREAD

**Issue by adolfotregosa** [HansKristian-Work/vkd3d-proton#1369]
Do the logs help in diagnosing the issue ? It shows startup video, when the option to press E to skip it and I press E,  game crashes. Tested several proton versions without success. 

[steam-1449560.log](https://github.com/HansKristian-Work/vkd3d-proton/files/10367205/steam-1449560.log)
[vkd3d_metro.log](https://github.com/HansKristian-Work/vkd3d-proton/files/10367206/vkd3d_metro.log)

EDIT: Crash is only present with nvidia driver 525.xx , 520.xx works fine. Any workaround for 525.xx ??

**Comment by eXt73** [comment]
I can confirm when ray tracing is on it crashes immediately. Tested on RTXC 4070 Ti

**Comment by xPakrikx** [comment]
yup same on my Fedora 37 + 4070 Ti. Just black screen right after intro

**Comment by philipl** [comment]
Did you also get this in `dmesg`?

```
[73868.757423] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics SM Warp Exception on (GPC 0, TPC 4, SM 0): Illegal Instruction Parameter
[73868.757452] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics SM Global Exception on (GPC 0, TPC 4, SM 0): Multiple Warp Errors
[73868.757477] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: ESR 0x506730=0x5000b 0x506734=0x4 0x506728=0xf812b60 0x50672c=0x1104
[73873.005746] NVRM: Xid (PCI:0000:01:00): 109, pid=210462, name=MetroExodus.exe, Ch 00000046, errorString CTX SWITCH TIMEOUT, Info 0x19c02f
```

**Comment by eXt73** [comment]
> Did you also get this in `dmesg`?
> 
> ```
> [73868.757423] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics SM Warp Exception on (GPC 0, TPC 4, SM 0): Illegal Instruction Parameter
> [73868.757452] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics SM Global Exception on (GPC 0, TPC 4, SM 0): Multiple Warp Errors
> [73868.757477] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: ESR 0x506730=0x5000b 0x506734=0x4 0x506728=0xf812b60 0x50672c=0x1104
> [73873.005746] NVRM: Xid (PCI:0000:01:00): 109, pid=210462, name=MetroExodus.exe, Ch 00000046, errorString CTX SWITCH TIMEOUT, Info 0x19c02f
> ```

These are errors of the 525.xx drivers - for sure for the 40xx line. I experience this mainly on Cyberpunk 2077

**Comment by philipl** [comment]
Still happens with 530 drivers. Sad panda.

**Comment by Blisto91** [comment]
@adolfotregosa could you give this a try again with the newest Nvidia driver?

**Comment by Mr-Blue-Sky-Candy** [comment]
@adolfotregosa how do you run Metro Exodus Enhanced edition? Do you use any lunch options?

I start the game with the lunch options: `VKD3D_FEATURE_LEVEL=12_2 VKD3D_CONFIG=dxr11 PROTON_HIDE_NVIDIA_GPU=0 PROTON_ENABLE_NVAPI=1 %command%`. Otherwise, it doesn't run with an error saying dxr is missing. 

These are all the log files in my HOME folder that are related to Metro Exodus Enhanced edition:
[metroexodus.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12342386/metroexodus.log)
[MetroExodus_304.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12342393/MetroExodus_304.log)

Let me know if I can clarify this better or help in any way.

**Comment by adolfotregosa** [comment]
> @adolfotregosa how do you run Metro Exodus Enhanced edition? Do you use any lunch options?
> 
> I start the game with the lunch options: `VKD3D_FEATURE_LEVEL=12_2 VKD3D_CONFIG=dxr11 PROTON_HIDE_NVIDIA_GPU=0 PROTON_ENABLE_NVAPI=1 %command%`. Otherwise, it doesn't run with an error saying dxr is missing. With these options, it points me to the following error report: [MetroExodus_error_report_230815-103015.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/12342457/MetroExodus_error_report_230815-103015.zip)
> 
> These are all the other log files in my HOME folder that are related to Metro Exodus Enhanced edition: [metroexodus.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12342386/metroexodus.log) [MetroExodus_304.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12342393/MetroExodus_304.log)
> 
> Let me know if I can clarify this better or help in any way.

![versions](https://github.com/HansKristian-Work/vkd3d-proton/assets/7437931/3fb6aae7-387e-4546-9618-e698f9d7e438)

proton-ge 8.11
mangohud gamemoderun VKD3D_CONFIG=dxr11 PROTON_ENABLE_NVAPI=1 %command%

![game](https://github.com/HansKristian-Work/vkd3d-proton/assets/7437931/a1023877-2fc5-48f1-bb57-b7578dfa6174)

**Comment by philipl** [comment]
For the first time since Feb 2023, I was able to get the game to run today after upgrading to the nvidia 550 drivers (and using whatever proton experimental is current as of today).

I had `VKD3D_CONFIG=dxr11 VKD3D_FEATURE_LEVEL=12_2 PROTON_ENABLE_NVAPI=1` set, although I haven't yet checked if any of those are actually necessary at this point. I think they may all be default for the current versions of everything.

I did not turn on hairworks as I've read that still crashes.
