### ISSUE TITLE
Witcher 3 RT shadows are broken

### ISSUE THREAD

**Issue by K0bin** [HansKristian-Work/vkd3d-proton#1373]
After walking for a couple of meters, this happens:

![20230112015841_1](https://user-images.githubusercontent.com/1131720/211952367-e56d37bd-9afe-420f-92a3-8818e1f9edc6.jpg)

**Comment by janos666** [comment]
How did you even get the game running at all?
I dropped in the d3d12.dll from vkd3d-proton-2.8 and dxgi.dll from dxvk-2.1. TW3 4.0.2 stars up and the menu is working (NVAPI-dependent features and RT are both grayed out -> the first is expected, the latter is not so much) but upon loading a save file the game hangs up with a black screen (background music continues to play but the image is not refreshed, the RTSS overlay is also frozen).

**Comment by K0bin** [comment]
@janos666 There is absolutely no reason to use vkd3d-Proton on Windows. It's not gonna run faster.

**Comment by janos666** [comment]
> @janos666 There is absolutely no reason to use vkd3d-Proton on Windows. It's not gonna run faster.
I was simply curious because I got ~17% higher fps with D11+DXVK compared to native DX11 but DX12 is ~50% slower than native DX11.

**Comment by K0bin** [comment]
The shadow issue is likely a bug on our end, it's just extremely difficult to fix.

**Comment by K0bin** [comment]
The shadow issue is likely a bug on our end, it's just extremely difficult to fix.

**Comment by CarlKath** [comment]
I am on Arch and wondering too how you got it to work. I start the game with these arguments: "VKD3D_CONFIG=dxr11,dxr PROTON_ENABLE_NVAPI=1 PROTON_ENABLE_NGX_UPDATER=1 %command% --launcher-skip"

The menu loads flawless and i can set the settings, when Ray Tracing is enabled i get a black screen or hanging screen without seeing an in game image. Sound works, i still hear Witcher sound. In the system, the Witcher MainThread process is shown as inactive.

The last few lines in the log are these:
"2307.993:013c:04d0:trace:unwind:dump_unwind_info     0x4: subq $0x28,%rsp
2307.993:013c:04d0:trace:unwind:dump_unwind_info     handler 0000000141840F98 data at 0000000143728304
2307.993:013c:04d0:trace:unwind:call_unwind_handler calling handler 0000000141840F98 (rec=00000002BAE1EB30, frame=00000002BAE1FDB0 context=00000002BAE1F140, dispatch=00000002BAE1E4F0)
2307.993:013c:04d0:trace:unwind:call_unwind_handler handler 0000000141840F98 returned 1
2307.993:013c:04d0:trace:seh:RtlRestoreContext calling consolidate callback 000000014184506C (rec=00000002BAE1EB30)
2307.993:013c:04d0:trace:seh:RtlRestoreContext returning to 0000000141CE1CFD stack 00000002BAE1FDB0
2308.292:013c:043c:warn:vkd3d-proton:d3d12_pipeline_state_init_graphics_create_info: Ignoring stencilTestEnable due to lack of stencil aspect.
2308.330:013c:045c:warn:vkd3d-proton:d3d12_pipeline_state_init_graphics_create_info: DSV format is DXGI_FORMAT_UNKNOWN.
2308.987:013c:022c:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Pipeline cache marked dirty. Flush is scheduled.
2309.023:013c:025c:warn:vkd3d-proton:d3d12_resource_QueryInterface: {aec22fb8-76f3-4639-9be0-28eb43a67a2e} not implemented, returning E_NOINTERFACE.
2309.023:013c:025c:warn:vkd3d-proton:d3d12_resource_QueryInterface: {aec22fb8-76f3-4639-9be0-28eb43a67a2e} not implemented, returning E_NOINTERFACE.
2309.024:013c:025c:warn:vkd3d-proton:d3d12_resource_QueryInterface: {aec22fb8-76f3-4639-9be0-28eb43a67a2e} not implemented, returning E_NOINTERFACE.
2309.169:013c:042c:warn:vkd3d-proton:d3d12_pipeline_state_init_graphics_create_info: DSV format is DXGI_FORMAT_UNKNOWN.
2310.082:013c:022c:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Flushing disk cache (wakeup counter since last flush = 46). It seems like application has stopped creating new PSOs for the time being.
2318.448:010c:011c:fixme:oleacc:find_class_data unhandled window class: L"#32769"
2318.448:010c:011c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
2318.448:010c:011c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
2318.451:010c:011c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
2318.451:010c:011c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
2318.451:010c:011c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
2318.451:010c:011c:fixme:uiautomation:nc_provider_GetPatternProvider 00000000004B7370, 10002, 0000000001B2EC90: stub
2318.451:010c:011c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00000000004B72E0, 10002, 0000000001B2EC90: stub
2355.780:00e4:04e0:warn:threadname:NtSetInformationThread Thread renamed to L"wine_threadpool_worker"
2355.799:0030:04e4:warn:threadname:NtSetInformationThread Thread renamed to L"wine_threadpool_worker"
2355.800:0030:04e8:warn:threadname:NtSetInformationThread Thread renamed to L"wine_threadpool_worker"
2355.802:0030:04ec:warn:threadname:NtSetInformationThread Thread renamed to L"wine_threadpool_worker"
2355.803:0030:04f0:warn:threadname:NtSetInformationThread Thread renamed to L"wine_threadpool_worker"
2355.803:0030:04f4:warn:threadname:NtSetInformationThread Thread renamed to L"wine_threadpool_worker"
pid 11602 != 11601, skipping destruction (fork without exec?)"

Thank you for reading. :)

**Comment by K0bin** [comment]
@CarlKath The game just hangs on Nvidia GPUs with RT enabled. I got in game with a shitty hack that impacts performance but we're not gonna ship that.

Unfortunately it's impossible to debug what's going wrong. It very much looks like a driver bug.

**Comment by oscarbg** [comment]
@K0bin nvidia is aware of this possible driver bug, to help?

**Comment by CarlKath** [comment]
> @CarlKath The game just hangs on Nvidia GPUs with RT enabled. I got in game with a shitty hack that impacts performance but we're not gonna ship that.
> 
> Unfortunately it's impossible to debug what's going wrong. It very much looks like a driver bug.

More than understandable that you don't want to release half-baked code if it's not enough pleasant to game with it.

I thought it would be "okay" with RT Shadows disabled.

Thank you very much for the fast and nice reply! (:

In ProtonDB are a few guys that mentioned to running the game with RT, I was really wondering what's not okay with my configuration.

**Comment by CarlKath** [comment]
> @K0bin nvidia is aware of this possible driver bug, to help?

I don't think nVidia will be addressing any problems with VKD3D.

**Comment by mbriar** [comment]
> I don't think nVidia will be addressing any problems with VKD3D.

of course they would, they have contributed to vkd3d-proton before and also support DLSS with it.

**Comment by CarlKath** [comment]
> > I don't think nVidia will be addressing any problems with VKD3D.
> 
> 
> 
> of course they would, they have contributed to vkd3d-proton before and also support DLSS with it.

Okay, thank you very much for the surprise!
I thought it was all work by the community.
