### ISSUE TITLE
Is possible install vkd3d proton 2.6 inside Steam ?

### ISSUE THREAD

**Issue by Augusto7743** [HansKristian-Work/vkd3d-proton#1703]
Hello.
Thanks for reading my topic.
Here Ubuntu 20.04.6 and Steam updated version.
Video card is an GT 640 vulkan 1.2. vkd3d proton 2.6 is the last version for vulkan 1.2 drivers.
In Steam when selecting to download an DX12 game for test was automatically downloaded "Proton Experimental" and "Linux Runtime sniper".
Possibly Steam have an component to run the DX12 in Linux. However is big chance not will work with my kepler video card.
Thus being an possible solution is try install vkd3d-proton 2.6.
I have vkd3d-proton in WINE, but is as Steam use an alternative solution to run windows games in Linux.

How install vkd3d-proton inside Steam ? Is possible ? Where have the information to do it ?

Have an nice week.

**Comment by K0bin** [comment]
Older versions of VKD3D-Proton won't work on Kepler GPUs either.

**Comment by Augusto7743** [comment]
Thanks for replying.
What ? Here I had posted an old topic about what VKD3D-Proton last version having support for Nvidia driver 470 and vulkan 1.2 and the reply was VKD3D-Proton 2.6.

You are saying even VKD3D-Proton 2.6 requiring driver with vulkan 1.2 not work for GF 600 series kepler ?

**Comment by Blisto91** [comment]
The easy way would be to just use last Proton 7.0 stable which ships that last version before the driver bump was actual.
If it's because you want to use a older vkd3d-proton version in  e.g. proton Experimental then the most "correct" way would be to replace the files that is shipped with that version with the ones you want to use.
Their location in Experimental for 32-bit and 64-bit respectively would then be
```
~/.steam/steam/steamapps/common/Proton - Experimental/files/lib/wine/vkd3d-proton/
```
```
~/.steam/steam/steamapps/common/Proton - Experimental/files/lib64/wine/vkd3d-proton/
```
And you'd then have to do the same again with dxvk in the dxvk folder as that is also required for vkd3d-proton to work properly. 1.10.3 should do.
Though note when Experimental updates the files will be overwritten and you'll have to do it over again (using stable proton 8 would keep the files alive for longer). Also this state will probably be considered unsupported from a official Proton perspective.

The third way which I'd consider "uncorrect" would be to just slap the correct bitness of old dxvk and vkd3d-proton DLLs you want to use next to a games exe. But this could get messy with some games wanting to partly use DLLs from the prefix system folder (if hardcoded path) and partly the ones next to exe. So might not work always in practice.

**Comment by Augusto7743** [comment]
@Blisto91

Thanks very much for your reply =)

The last Proton version using vulkan 1.2 is 7.0-6.
About move files is simple. However dxvk and vkd3d-proton does any change settings in files and in wine registry ?

An nice week for you.

**Comment by Blisto91** [comment]
Shouldn't need any other changes than moving the files.

Note, as I believe K0bin hinted at above, that Kepler was always a bit extra special even back when it's driver versions was supported. It tended to have extra issues compared to newer GPU generations even on the same drivers so can't promise things will go smoothly.
