### ISSUE TITLE
Meson-git breaks build

### ISSUE THREAD

**Issue by ms178** [HansKristian-Work/vkd3d-proton#1770]
Usign meson-git (1.3.0rc1.r13.2d538c58c), the build now fails early on with:

```
vkd3d-proton/libs/d3d12core/meson.build:15:16: ERROR: shared_library keyword argument "objects" File: "d3d12core.def" are not objects

A full log can be found at /tmp/makepkg/vkd3d-proton-mingw-git/src/build/x64/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```

**Comment by ionenwks** [comment]
For the record this should be fixed on meson's end (will be in upcoming >=1.3.0rc3) to emit a deprecation warning instead, see https://github.com/mesonbuild/meson/pull/12508

Not that the warning shouldn't be fixed here either way to avoid future issues.

**Comment by HansKristian-Work** [comment]
The suggested fix to use vs_module_def breaks the build since MinGW targets ignore that apparently. We cannot fix this as-is.

**Comment by eli-schwartz** [comment]
I was a bit afraid of that but I didn't have the toolchain to build this locally.

It's a confusing situation since it was silently allowed for source files but not permitted for custom_target outputs... We really should be consistent and allow both. Well actually we should fix vs_module_defs to work correctly.
