### ISSUE TITLE
Hitman 2 Crashes

### ISSUE THREAD

**Issue by FaithLV** [HansKristian-Work/vkd3d-proton#180]
Launching Hitman 2 with `DirectX 12` crashes the game after pressing Play. 
Tested with `Proton 5.0.9` with and without `ACO`.

Proton log: https://gist.github.com/FaithLV/3ecbbc04d0f4c2fd010019d28fd2e949

### System Information

AMD FX-8300
RX 590
5.7.6-zen1-1-zen

Full Information: https://gist.githubusercontent.com/FaithLV/c3e0bb9bf3d02b2d42220e3ad984b7f0/raw/d94e1ce3582da67a2ead11222630bfc56693800a/steam-system

**Comment by doitsujin** [comment]
This is a wine bug, the DXGI implementation is missing functionality for this game. It (kind of) works with a standalone d3d12.dll build combined with the DXGI implementation from DXVK.

**Comment by FaithLV** [comment]
As I understand, I need to build on Windows to get a standalone .exe?

**Comment by doitsujin** [comment]
no, but you need mingw to cross-compile on Linux.

**Comment by MegWATTT** [comment]
You can use DirectX 12 with the latest RC of Proton 5.0-10. You just need to add the environment variable `WINEDLLOVERRIDES=dxgi=n` in order to use DXGI from DXVK.
Performance is impressive (not too different from d3d11), but with more stutter.
I however have a glitch where some lights have wrong color and power. It seems to be a bit random as affected lights aren't always the same.
![Capture d’écran de 2020-07-25 16-44-47](https://user-images.githubusercontent.com/9790221/88464772-b6d87000-cebd-11ea-8b92-1fe0182d023f.png)
Same issue with both RADV and AMDVLK.

**Comment by FaithLV** [comment]
Closing as it's a wine bug.
