### ISSUE TITLE
Can this be ported to mac?

### ISSUE THREAD

**Issue by iiasceri** [HansKristian-Work/vkd3d-proton#1889]
Project below works just fine with crossover and any launcher wrap up:
https://github.com/Gcenx/DXVK-macOS

but its downside: doesn't support dx 12.

Since this is linux oriented how hard is this to be ported to ARM / Apple Silicon?
I am willing to work on that but before I start doing anything I wanted to see what 1-2 devs opinion is.

**Comment by K0bin** [comment]
> Project below works just fine with crossover and any launcher wrap up:
https://github.com/Gcenx/DXVK-macOS

Not really. That's an older version of DXVK because the latest version doesn't work. On top of that it just ignores a bunch of D3D11 features because Metal and MoltenVK don't have a direct equivalent. 

VKD3D-Proton doesn't work on Mac OS because MoltenVK is missing a lot of features that D3D12 games actually rely on.

Some of the most problematic ones are:

- Bindless (proper support for VK_EXT_descriptor_indexing or VK_EXT_descriptor_buffer + VK_EXT_mutable_descriptor_type)
- Sparse resources
