### ISSUE TITLE
Alan Wake 2 - freeze and crash after short time of playing when using path tracing

### ISSUE THREAD

**Issue by owynek** [HansKristian-Work/vkd3d-proton#1917]
Game freezes when playing with path tracing turned on. 
There is a message constantly showing in log: Requesting scratch buffer kind 0 larger than limit (8294400 > 1048576). Expect bad performance.

### Software information
Alan Wake 2 - very high settings, path tracing turned on

### System information
- GPU: NVIDIA GeForce RTX 4080
- Driver: NVIDIA 550.54.14
- Wine version: wine-ge-8-22
- VKD3D-Proton version: 2.11.1

### Log files
[alan.log](https://github.com/HansKristian-Work/vkd3d-proton/files/14427163/alan.log)

**Comment by Blisto91** [comment]
Might be interesting to give it a go with latest master if you can https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/8046743657

**Comment by owynek** [comment]
Thanks for advice, didn't help though.

**Comment by Blisto91** [comment]
@owynek  Newly released driver might be worth a go https://www.nvidia.co.uk/download/driverResults.aspx/223635/en-uk

> Fixed Xid error when playing Alan Wake 2 with ray tracing enabled.

**Comment by owynek** [comment]
It did help, thank you for advices. I'll close this issue

**Comment by OneNot** [comment]
I believe I'm seeing the same underlying issue still in 07/2026. Or at least, I'm seeing the same error messages. Instead of a crash/freeze, I'm seeing framerate randomly tank to **exactly** 10FPS (or 20 with FG) for anywhere between a few seconds to a few minutes at a time. After it recovers, it holds steady at my normal cap of 97FPS (for VRR reasons on a 100Hz refresh rate monitor) until it randomly tanks again later.

System:
CPU: 13900K
RAM: 64GB
GPU: 4090
Driver: NVIDIA 610.43.3
Distro: CachyOS Linux 7.1.3-2-cachyos
Launcher: Heroic 2.22.0 Hajrudin, Legendary 0.20.43 (Riding Shotgun)
Runtime: umu-launcher 1.4.0, steamrt4
Proton: Proton-CachyOS Latest (11.0)
vkd3d-proton build: ee737e324376289
DXVK: v2.7.1-788-g30f6f8338e3f88a

Log excerpt:
```log
18528.604:0150:0238:fixme:vkd3d-proton:d3d12_device_get_scratch_buffer: Requesting scratch buffer kind 0 larger than limit (4953600 > 1048576). Expect bad performance.
``` 

[full log from Heroic Launcher](https://github.com/user-attachments/files/29943365/launch.log)
