### ISSUE TITLE
Grid (2019) crashes since commit 49d3fa30a79d65e69d3f39d3b4cccf06d0e512a8

### ISSUE THREAD

**Issue by NoXPhasma** [HansKristian-Work/vkd3d-proton#402]
As already reported in the [Proton issue tracker](https://github.com/ValveSoftware/Proton/issues/3143#issuecomment-727638255), Grid (2019) crashes with Proton 5.13-2 but worked with 5.13-1. I was able to bicect it to 49d3fa30a79d65e69d3f39d3b4cccf06d0e512a8:
```
❯ git bisect bad
49d3fa30a79d65e69d3f39d3b4cccf06d0e512a8 is the first bad commit
commit 49d3fa30a79d65e69d3f39d3b4cccf06d0e512a8
Author: Philip Rebohle <philip.rebohle@tu-dortmund.de>
Date:   Fri Oct 23 14:00:18 2020 +0200

    vkd3d: Enable offset buffer as necessary.
    
    Signed-off-by: Philip Rebohle <philip.rebohle@tu-dortmund.de>

 libs/vkd3d/state.c | 10 +++++++---
 1 file changed, 7 insertions(+), 3 deletions(-)
```

**Comment by NoXPhasma** [comment]
Using `VKD3D_CONFIG=force_bindless_texel_buffer %command%` on latest master fixes this issue.

**Comment by MagicD3VIL** [comment]
I tried the command on Proton 5.13-2 and the problem persists.

The game still crashes my X session (and Plasma ofc) after I supposedly get to the Main menu (sounds and navigating the menu works since you can hear the sounds of it). 

Before the crash happens there are flickering white artifacts on the screen and the text on screen about epilepsy is also flickering _(the irony right)_. 

Any way to get the log out of the Proton if it caught anything regarding the graphics card?

**Comment by NoXPhasma** [comment]
@MagicD3VIL You need to compile the latest master of this repository. The option I mentioned above is not available in the proton-vkd3d version of Proton 5.13-2

**Comment by SmileEdge** [comment]
Any news on this ?

**Comment by leillo1975** [comment]
They forgot us....

**Comment by K0bin** [comment]
No they didn't, the original issue is fixed in master.

**Comment by NoXPhasma** [comment]
Since this has been fixed I will close this issue.
