### ISSUE TITLE
Major Performance Issues: Horizon Zero Dawn

### ISSUE THREAD

**Issue by JW6677** [HansKristian-Work/vkd3d-proton#430]
On my 5700xt I am only getting around 10% GPU usage according to MangoHUD and only 40FPS on "original" quality settings. On Windows I can get over 200 FPS on ultra. My launch options are "gamemoderun mangohud RADV_PERFTEST=aco PROTON_NO_ESYNC=1 PULSE_LATENCY_MSEC=60 %command%" Using Proton-5.21-GE-1.

**Comment by ngoquang2708** [comment]
I have the same issue and already mentioned it 
[here](https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-733794531). There are others mentioned the same issue too.

**Comment by K0bin** [comment]
Why do you disable Esync?

**Comment by doitsujin** [comment]
Disabling esync sounds like a bad idea and could very well be responsible for bad perf.

> On Windows I can get over 200 FPS on ultra.

This sounds completely unrealistic. What resolution, CPU, and which part of the game are giving you that kind of frame rate?

**Comment by SveSop** [comment]
> 
> 
> Why do you disable Esync?

Would it matter if you use PROTON_NO_ESYNC=1 since not specifying PROTON_NO_FSYNC=1 would mean that would be used instead (as long as a fsync patched kernel is used ofc). You can't really use esync when you are using fsync, and as long as a fsync-enabled kernel is used, the default (unless specified) is to use FSYNC - thus explicitly disabling ESYNC does not really matter, other than it is kinda a moot thing to do...

Or do i miss something?

[https://github.com/ValveSoftware/wine/blob/d6646652a2f5f85d51fab5df3383f04bef713a18/dlls/ntdll/unix/esync.c#L71](https://github.com/ValveSoftware/wine/blob/d6646652a2f5f85d51fab5df3383f04bef713a18/dlls/ntdll/unix/esync.c#L71)

**Comment by HansKristian-Work** [comment]
Isn't this the Wine sqrt() performance bug?

**Comment by JW6677** [comment]
I will try without esync. It must have been left over when I copied over the launch options from doom 2016 and I think I forgot to remove it. Hang on

**Comment by JW6677** [comment]
It could possibly be mangohud reporting it wrong. I wouldn't be surprised.

**Comment by JW6677** [comment]
Ok, So I've done some testing and removing PROTON_NO_ESYNC=1 actually helped quite a bit netting me around an extra 10 FPS. I also installed CoreCTRL and saw that mangohud is incorrectly calculating the GPU usage as on CoreCTRL I can see that my GPU is at 99%. With the improvements I can get around 40 FPS when looking at Mother's Crown in Horizon on Ultra so a good improvement. Still not at the performance I am getting with windows 10 at ultra but not bad for early DX12 conversion. Thanks for the help!

**Comment by ngoquang2708** [comment]
@JW6677 Ignore the fps, how about the audio desync?

**Comment by phush0** [comment]
How about slow motion video and normal audio ?

**Comment by ErikReider** [comment]
40fps on ultra? I'm getting 12 fps with low CPU and GPU usage on my Ryzen 5800X and my 5700XT. Even setting the CPU governor to power saving (from performance) doesn't affect the fps so something's wrong
